// Tergush'tekhn

IF
    Global("REGRET","GLOBAL",1)
	Global("G-BBTRGT","GLOBAL",0)
		
THEN
    RESPONSE #100
		Wait(2)
        CreateCreature("g-bb051",[339.610],14)
        SetGlobal("G-BBTRGT","GLOBAL",1)
		ActionOverride("AETHEL",DestroySelf()) 
		ActionOverride("g-bbteg",DestroySelf())
		Wait(3)
		CreateCreature("AETHEL",[318.680],NE)
		CreateCreature("g-bbteg",[411.580],4)	
		ChangeDialog("AETHEL","g-bbdaet")
		ChangeDialog("g-bbteg","g-bbdteg") 
		ActionOverride("g-bbteg",ChangeAIScript("g-bbteg",DEFAULT))
		ActionOverride("AETHEL",ChangeAIScript("0402athl",DEFAULT))
		Wait(1)	
		ChangeDialog("AETHEL","g-bbdaet")
		ChangeDialog("g-bbteg","g-bbdteg") 
				
END

IF
    Dead("g-bb051")
THEN
    RESPONSE #100
    SetGlobal("Game_Over","GLOBAL",3)
END

IF
		Global("G-intro_mov","GLOBAL",1)
THEN
    RESPONSE #100
		SetGlobal("G-intro_mov","GLOBAL",2)
		//StartMovie("g-memo")
		ActionOverride("g-bb051",StartDialogNoSet(Player1))
END

