# Never copy this file from other mods, always use https://github.com/ALIENQuake/ProjectInfinity/wiki/Adding-metadata-for-mod
# Filename must be the same as tp2 basename, placed in the same folder where
# .tp2 file is located, use UTF8 (without BOM) encoding, everything is optional

# ini section header is required to avoid false detection
[Metadata]

# Full name of the mod, without the list of supported games, without the version number, without 'Mod'
Name = Blizzard in Baator

# Author name or nick, don't use an email address
Author = Cania Believe It Works team

# Short description of the mod, main goals, features etc
Description = A fully playable Act 1 for the largest mod ever for Planescape: Torment - EE. It's a whole new chapter in the story of The Nameless One crafted in over 2.5 years by over 30 people.

# Web address of mod readme file (filename is case-sensitive!), comma-separated list. You can link to txt, md, html, pdf etc.
Readme = https://github.com/BallDamage312/blizzard-in-baator/blob/main/README.md, https://github.com/BallDamage312/blizzard-in-baator/blob/main/README_pl.md

# Web address of mod dedicated forum or forum thread 
Forum = https://www.gibberlings3.net/forums/topic/39952-story-modplanescape-torment-enhanced-edition-blizzard-in-baator-act-1/

# Web address of mod personal Homepage, no need to duplicate with a mod dedicated forum
# Homepage = https://www.example.com

# If you use GitHub.com, simply use https://github.com/AccountOrOrgName/RepositoryName (omit /releases)
# read more about Delta Updates https://github.com/ALIENQuake/ProjectInfinity/wiki/Delta-Updates-for-mods-hosted-at-Github
Download = https://github.com/BallDamage312/blizzard-in-baator/

# Type of LABELs used by the mod, read more here https://www.gibberlings3.net/forums/topic/32516-tutorial-what-is-label
LabelType = GloballyUnique

# Dynamic Install Order, use mod ID as tp2 name without file extension and `setup-` prefix

# This mod must be installed *before* those ModID listed below, comma-separated list:
# Before = ModX, EET_end

# This mod must be installed *after* those ModID listed below, comma-separated list:
After = JournalPortraitConversation, Book Of Torment