; Berserker

[general]
animation_type=F000
move_scale=5.4
ellipse=16
color_blood=47
color_chunks=255
sound_freq=9
personal_space=3
cast_frame=4

[monster_planescape]
attack1=g-bbb042
attack2=g-bba042
stance2stand=g-bbc042
;stancefidget1=g-bbd042
diebackward=g-bbe042
;getup=g-bbf042
gethit=g-bbg042
run=g-bbp042
stand2stance=g-bbz042
standfidget1=g-bbj042
;spell1=g-bbk042
;spell2=g-bbl042
stance=g-bbm042
stand=g-bbn042
talk1=g-bbo042
walk=g-bbp042
;misc1-g-bbr042
;misc2=g-bbs042
;misc3=g-bbt042
runscale=16
bestiary=
armor=7

[sounds]
hitsound=cghit01,cghit02,cghit03
hitframe=0
dfbsound=CGDIE01,CGDIE02,CGDIE03
dfbframe=0
At1Sound=swi_02,swi_02a,swi_02c
At1frame=5
At2Sound=swi_02b,swi_02d,swi_02a
At2frame=5
