IF
    OnCreation()
THEN
    RESPONSE #100
        FaceObject([PC])
        SetItemFlags("COPPER",NONSTEALABLE,TRUE)  
        SetItemFlags("HEARCHRM",NONSTEALABLE,TRUE) 
        Continue()
END

IF
    Allegiance(Myself,ENEMY)
    Global("G-Kabatum_Kombat_N018","LOCALS",0)
    OR(2)
        See(NearestEnemyOf(Myself))
        Range([PC],25)
THEN
    RESPONSE #100
        FaceObject([PC])             
        SetGlobal("G-Kabatum_Kombat_N018","LOCALS",1) 
END

IF
    AttackedBy([PC],DEFAULT)
    Global("G-Kabatum_Kombat_N018","LOCALS",0)
THEN
    RESPONSE #100
        Enemy()
        FaceObject(LastAttackerOf(Myself))           
        FloatMessage(Myself,@100012)
        SetGlobal("G-Kabatum_Kombat_N018","LOCALS",1)
END

IF
    HPPercentLT(Myself,55)
    HasItem("HEARCHRM",Myself) 
THEN
    RESPONSE #100
        DisplayStringHead(Myself,30539)
        UseItem("HEARCHRM",Myself) 
        FaceObject([PC])
END

IF
    Allegiance(Myself,ENEMY)
    See(NearestEnemyOf(Myself))
    GlobalGT("G-Kabatum_Kombat_N018","LOCALS",0)
    !StateCheck(Myself,STATE_BLUR)
THEN
    RESPONSE #100
        ReallyForceSpell(Myself,WIZARD_BLUR)
        Continue()
END

IF
    See(NearestEnemyOf(Myself))
    Global("G-Kabatum_Kombat_N018","LOCALS",1)
THEN
    RESPONSE #100
        ReallyForceSpellRES("g-bb686",Myself)
        ReallyForceSpell(Myself,WIZARD_CLOAK_OF_WARDING)
        IncrementGlobal("G-Kabatum_Kombat_N018","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("G-Kabatum_Kombat_N018","LOCALS",2)
THEN
    RESPONSE #100
        Spell([PC],WIZARD_MISSILE_OF_PATIENCE) 
        IncrementGlobal("G-Kabatum_Kombat_N018","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("G-Kabatum_Kombat_N018","LOCALS",3)
THEN
    RESPONSE #100
        Spell([PC],WIZARD_BLINDNESS)
        IncrementGlobal("G-Kabatum_Kombat_N018","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("G-Kabatum_Kombat_N018","LOCALS",4)
THEN
    RESPONSE #100
        Spell([PC],WIZARD_HORROR) 
        IncrementGlobal("G-Kabatum_Kombat_N018","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("G-Kabatum_Kombat_N018","LOCALS",5)
THEN
    RESPONSE #100
        FloatMessage(Myself,@100011)
        Spell([PC],WIZARD_FORCE_MISSILES) 
        IncrementGlobal("G-Kabatum_Kombat_N018","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("G-Kabatum_Kombat_N018","LOCALS",6)
THEN
    RESPONSE #100
        Spell([PC],WIZARD_TONGUES_OF_FLAME) 
        IncrementGlobal("G-Kabatum_Kombat_N018","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("G-Kabatum_Kombat_N018","LOCALS",7)
THEN
    RESPONSE #100
        Spell([PC],WIZARD_FORCE_MISSILES) 
        IncrementGlobal("G-Kabatum_Kombat_N018","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("G-Kabatum_Kombat_N018","LOCALS",8)
THEN
    RESPONSE #100
        ForceSpellRES("g-bb668",NearestEnemyOf(Myself))
        IncrementGlobal("G-Kabatum_Kombat_N018","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("G-Kabatum_Kombat_N018","LOCALS",9)
THEN
    RESPONSE #100
        FloatMessage(Myself,@100013)
        ReallyForceSpell(Myself,WIZARD_BLUR)  
        IncrementGlobal("G-Kabatum_Kombat_N018","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("G-Kabatum_Kombat_N018","LOCALS",10)
THEN
    RESPONSE #100
        ReallyForceSpell(Myself,WIZARD_STRENGTH) 
        Spell([PC],WIZARD_MAGIC_MISSILE)          
        IncrementGlobal("G-Kabatum_Kombat_N018","LOCALS",1) 
END

IF
    See(NearestEnemyOf(Myself))
    GlobalGT("G-Kabatum_Kombat_N018","LOCALS",10) 
THEN
    RESPONSE #100
        RunningAttack(NearestEnemyOf(Myself))
END