IF
    OnCreation()
THEN
    RESPONSE #100
        FaceObject([PC])
        Continue()
END

IF
    HPPercentLT(Myself,30)
THEN
    RESPONSE #100
        ClearAllActions()
        ForceSpellRES("g-bb695",Player1)
        ForceSpell(Myself,CLERIC_CURE_CRITICAL_WOUNDS)
        JumpToObject([PC])
        RunningAttack(NearestEnemyOf(Myself))
END

IF
    HPPercentLT(Myself,60)
    HPPercentGT(Myself,30)
THEN
    RESPONSE #100
        ClearAllActions()
        ForceSpellRES("g-bb695",Player1)
        ForceSpell(Myself,CLERIC_CURE_MODERATE_WOUNDS)
        JumpToObject([PC])
        RunningAttack(NearestEnemyOf(Myself))
END

IF
    HPPercentLT(Myself,80)
    HPPercentGT(Myself,60)
THEN
    RESPONSE #100
        ClearAllActions()
        ForceSpellRES("g-bb695",Player1)
        ForceSpell(Myself,CLERIC_CURE_LIGHT_WOUNDS)
        JumpToObject([PC])
        RunningAttack(NearestEnemyOf(Myself))
END

IF
    See(NearestEnemyOf(Myself))
    Global("G-WArchon_Kombat_N034","LOCALS",1)
THEN
    RESPONSE #100
        ActionOverride(Player1,PlaySequence(ANIM_DIE))
        ActionOverride(Player2,PlaySequence(ANIM_DIE))
        ActionOverride(Player3,PlaySequence(ANIM_DIE))
        ActionOverride(Player4,PlaySequence(ANIM_DIE))
        ActionOverride(Player5,PlaySequence(ANIM_DIE))
        ActionOverride(Player6,PlaySequence(ANIM_DIE))
        Wait(1)
        ForceSpellRES("g-bb693",Player1)
        SmallWait(1)
        ActionOverride(Player1,PlaySequence(ANIM_GETUP))
        ActionOverride(Player2,PlaySequence(ANIM_GETUP))
        ActionOverride(Player3,PlaySequence(ANIM_GETUP))
        ActionOverride(Player4,PlaySequence(ANIM_GETUP))
        ActionOverride(Player5,PlaySequence(ANIM_GETUP))
        ActionOverride(Player6,PlaySequence(ANIM_GETUP))
        ForceSpell(Myself,CLERIC_PRAYER)
        ForceSpellRES("g-bb694",LastAttackerOf(Myself))
        Wait(1)
        FaceObject([PC])
        IncrementGlobal("G-WArchon_Kombat_N034","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("G-WArchon_Kombat_N034","LOCALS",2)
THEN
    RESPONSE #100
        ForceSpell([PC],CLERIC_HALO_OF_LESSER_REVELATION)
        Wait(1)
        IncrementGlobal("G-WArchon_Kombat_N034","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("G-WArchon_Kombat_N034","LOCALS",3)
THEN
    RESPONSE #100
        ForceSpellRES("g-bb686",Myself)
        IncrementGlobal("G-WArchon_Kombat_N034","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    GlobalGT("G-WArchon_Kombat_N034","LOCALS",3)
THEN
    RESPONSE #100
        JumpToObject([PC])
        RunningAttack(NearestEnemyOf(Myself))
END

IF
    Allegiance(Myself,ENEMY)
    Global("G-WArchon_Kombat_N034","LOCALS",0)
    OR(2)
        See(NearestEnemyOf(Myself))
        Range([PC],25)
THEN
    RESPONSE #100
        FaceObject([PC])             
        SetGlobal("G-WArchon_Kombat_N034","LOCALS",1) 
END

IF
    AttackedBy([PC],DEFAULT)
    Global("G-WArchon_Kombat_N034","LOCALS",0)
THEN
    RESPONSE #100
        Enemy()
        FaceObject(LastAttackerOf(Myself))           
        FloatMessage(Myself,@100016)
        SetGlobal("G-WArchon_Kombat_N034","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("G-WArchon_Kombat_N034","LOCALS",0)
THEN
    RESPONSE #100
        Enemy()
        JumpToObject([PC])
        RunningAttack(NearestEnemyOf(Myself))
        IncrementGlobal("G-WArchon_Kombat_N034","LOCALS",1)
END