// Tergush'tekhn

IF
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
		//SetGlobal("Game_Over","GLOBAL",1)
       RunningAttack(LastAttackerOf(Myself))
END

IF
    Global("g-fiendpanic","GLOBAL",1)
THEN
    RESPONSE #100
        Enemy()
        RunningAttack(LastAttackerOf(LastHelp))
END

IF
    AttackedBy([PC],DEFAULT)
THEN
    RESPONSE #100
		SetGlobal("g-fiendpanic","GLOBAL",1)
        Help()
        Enemy()
        RunningAttack(LastAttackerOf(Myself))
		
END

