IF
    See([PC])
    Global("G-Ratshaman_Kombat_001","LOCALS",1)
THEN
    RESPONSE #100
        ForceSpell([PC],CLERIC_CURSE)
        IncrementGlobal("G-Ratshaman_Kombat_001","LOCALS",1)
END

IF
    See([PC])
    Global("G-Ratshaman_Kombat_001","LOCALS",2)
THEN
    RESPONSE #100
        ForceSpell(NearestEnemyOf(Myself),WIZARD_VAMPIRIC_TOUCH)
        IncrementGlobal("G-Ratshaman_Kombat_001","LOCALS",1)
END

IF
    See([PC])
    Global("G-Ratshaman_Kombat_001","LOCALS",3)
THEN
    RESPONSE #100
        ForceSpell([PC],WIZARD_SWARM_CURSE)
        IncrementGlobal("G-Ratshaman_Kombat_001","LOCALS",1)
END

IF
    See([PC])
    Global("G-Ratshaman_Kombat_001","LOCALS",4)
THEN
    RESPONSE #100
        ForceSpell(LastSeenBy(Myself),WIZARD_CLOUDKILL)
        IncrementGlobal("G-Ratshaman_Kombat_001","LOCALS",1)
END

IF
    See([PC])
    Global("G-Ratshaman_Kombat_001","LOCALS",5)
THEN
    RESPONSE #100
        ForceSpell(NearestAllyOf(Myself),CLERIC_AID)
        IncrementGlobal("G-Ratshaman_Kombat_001","LOCALS",1)
END

IF
    See([PC])
    Global("G-Ratshaman_Kombat_001","LOCALS",6)
THEN
    RESPONSE #100
        ForceSpell([PC],CLERIC_SPIRITUAL_HAMMER)
        IncrementGlobal("G-Ratshaman_Kombat_001","LOCALS",1)
END

IF
    See([PC])
    Global("G-Ratshaman_Kombat_001","LOCALS",7)
THEN
    RESPONSE #100
        ForceSpell(NearestAllyOf(Myself),WIZARD_BLOOD_BRIDGE)
        IncrementGlobal("G-Ratshaman_Kombat_001","LOCALS",1)
END

IF
    See([PC])
    Global("G-Ratshaman_Kombat_001","LOCALS",8)
THEN
    RESPONSE #100
        ForceSpell([PC],WIZARD_IGNUS_FORCE_MISSILES)
        IncrementGlobal("G-Ratshaman_Kombat_001","LOCALS",1)
END

IF
    See([PC])
    Global("G-Ratshaman_Kombat_001","LOCALS",9)
THEN
    RESPONSE #100
        ForceSpell(NearestAllyOf(Myself),CLERIC_PRAYER)
        IncrementGlobal("G-Ratshaman_Kombat_001","LOCALS",1)
END

IF
    See([PC])
    GlobalGT("G-Ratshaman_Kombat_001","LOCALS",9)
THEN
    RESPONSE #100
        RunningAttack(NearestEnemyOf(Myself))
END

IF
    HPPercentLT(Myself,50)
THEN
    RESPONSE #100
        ClearAllActions()
        ForceSpell(Myself,CLERIC_CURE_SERIOUS_WOUNDS)
        RunningAttack(NearestEnemyOf(Myself))
END

IF
    AttackedBy([PC],DEFAULT)
    Global("G-Ratshaman_Kombat_001","LOCALS",0)
THEN
    RESPONSE #100
        Enemy()
        FaceObject(LastAttackerOf(Myself))
        SetGlobal("G-Ratshaman_Kombat_001","LOCALS",1)
END

IF
    Global("g-squerrikalert","GLOBAL",1)
    Global("G-Ratshaman_Kombat_001","LOCALS",0)
THEN
    RESPONSE #100
        FaceObject([PC])
        Help()
        Enemy()
        SetGlobal("G-Ratshaman_Kombat_001","LOCALS",1)
END

IF
    See(NearestEnemyOf(Myself))
    Global("G-Ratshaman_Kombat_001","LOCALS",0)
THEN
    RESPONSE #100
        Enemy()
        SetGlobal("G-Ratshaman_Kombat_001","LOCALS",1)
END