; Gelugon

[general]
animation_type=F000
move_scale=5.3
ellipse=17
color_blood=47
color_chunks=255
sound_freq=9
personal_space=3
cast_frame=3

[monster_planescape]
attack1=g-bba034
attack2=g-bbb034
stance2stand=g-bbm034
;stancefidget1=g-bbd0
diebackward=g-bbe034
;getup=g-bbf0
gethit=g-bbg034
run=g-bbh034
stand2stance=g-bbm034
;standfidget1=g-bbj0
;spell1=g-bbk0
;spell2=g-bbl0
stance=g-bbm034
stand=g-bbm034
;talk1=g-bbo0
walk=g-bbp034
runscale=16
bestiary=1015
;armor=

[sounds]
;hitsound=
;hitframe=0
;dfbsound=
;dfbframe=8
;At1Sound=
;At1frame=6
;At2Sound=
;At2frame=4
;Cf1Sound=
;Cf1frame=3
